-- Deploy all PostgreSQL schema objects for the TextureGen3D template.
-- This file is auto-generated by gulpfile.js in the TextureGen3D.SQL project.
-- Run this script against a default database (e.g., template1); it creates the application database if it does not exist.

SELECT 'CREATE DATABASE texturegen3d' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'texturegen3d')
\gexec
\connect texturegen3d

-- Tables
\i Tables/AppRoles.sql
\i Tables/AppUsers.sql
\i Tables/AppUserRoles.sql
\i Tables/AppUserTokens.sql

-- Sequences
\i Sequences/SequenceAppRoles.sql
\i Sequences/SequenceAppUserTokens.sql

-- Indexes
\i Indexes/IndexAppUsersEmail.sql

-- Functions
\i Functions/ResetSequences.sql

-- SeedData
\i SeedData/AppRoles.sql
