const gulp = require('gulp');
const fs = require('fs');
const path = require('path');

const deployFile = 'deploy.sql';

function parseArgs() {
  const args = {};
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].substring(2).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
      const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : 'true';
      args[key] = value;
      if (value !== 'true') i++;
    }
  }
  return args;
}

// Ordered list of schema subfolders. SeedData runs last so all schema objects exist first.
const schemaFolders = [
  'Tables',
  'Sequences',
  'Indexes',
  'Functions',
  'Views',
  'SeedData'
];

// Optional explicit per-folder file order. Missing files are ignored; unlisted files are sorted alphabetically.
const folderOrder = {};

function extractTableName(sql) {
  const match = sql.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:\w+\.)?["']?(\w+)["']?/i);
  return match ? match[1] : null;
}

function extractReferences(sql) {
  const refs = [];
  const regex = /REFERENCES\s+(?:\w+\.)?["']?(\w+)["']?\s*\(/gi;
  let match;
  while ((match = regex.exec(sql)) !== null) {
    refs.push(match[1]);
  }
  return refs;
}

function sortByDependencies(files, folder) {
  const fileContents = {};
  const tableToFile = {};
  const dependencies = {};

  for (const file of files) {
    const sql = fs.readFileSync(path.join(__dirname, folder, file), 'utf8');
    fileContents[file] = sql;
    const table = extractTableName(sql);
    if (table) {
      tableToFile[table] = file;
    }
    dependencies[file] = new Set();
  }

  for (const file of files) {
    const refs = extractReferences(fileContents[file]);
    for (const ref of refs) {
      if (tableToFile[ref] && tableToFile[ref] !== file) {
        dependencies[file].add(tableToFile[ref]);
      }
    }
  }

  const inDegree = {};
  for (const file of files) {
    inDegree[file] = dependencies[file].size;
  }

  const queue = files.filter(f => inDegree[f] === 0).sort();
  const result = [];
  while (queue.length > 0) {
    const current = queue.shift();
    result.push(current);
    for (const file of files) {
      if (dependencies[file].has(current)) {
        inDegree[file]--;
        if (inDegree[file] === 0) {
          queue.push(file);
          queue.sort();
        }
      }
    }
  }

  if (result.length !== files.length) {
    const remaining = files.filter(f => !result.includes(f)).sort();
    console.warn(`Circular dependency detected in ${folder}. Appending remaining files alphabetically: ${remaining.join(', ')}`);
    result.push(...remaining);
  }

  return result;
}

function getSqlFiles(folder) {
  const fullPath = path.join(__dirname, folder);
  if (!fs.existsSync(fullPath)) {
    return [];
  }

  const files = [];
  function collect(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const entryPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        collect(entryPath);
      } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.sql') && entry.name.toLowerCase() !== deployFile.toLowerCase()) {
        files.push(entryPath);
      }
    }
  }
  collect(fullPath);

  const relativeFiles = files.map(file => path.relative(fullPath, file).replace(/\\/g, '/'));

  const order = folderOrder[folder];
  if (order) {
    const ordered = [];
    const remaining = new Set(relativeFiles);
    for (const file of order) {
      if (remaining.has(file)) {
        ordered.push(file);
        remaining.delete(file);
      }
    }
    return ordered.concat([...remaining].sort());
  }

  if (folder === 'Tables') {
    return sortByDependencies(relativeFiles, folder);
  }

  return relativeFiles.sort();
}

function generateDeployContent(args) {
  const options = args || {};
  const dbName = (options.database || 'texturegen3d').toLowerCase();
  const lines = [
    '-- Deploy all PostgreSQL schema objects for the TextureGen3D template.',
    '-- This file is auto-generated by gulpfile.js in the TextureGen3D.SQL project.',
    '-- Run this script against a default database (e.g., template1); it creates the application database if it does not exist.',
    '',
    `SELECT 'CREATE DATABASE ${dbName}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${dbName}')`,
    `\\gexec`,
    `\\connect ${dbName}`,
    ''
  ];

  for (const folder of schemaFolders) {
    const files = getSqlFiles(folder);
    if (files.length === 0) {
      continue;
    }
    lines.push(`-- ${folder}`);
    for (const file of files) {
      lines.push(`\\i ${folder}/${file}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function updateDeploy() {
  const args = parseArgs();
  const content = generateDeployContent(args);
  fs.writeFileSync(path.join(__dirname, deployFile), content, 'utf8');
  console.log(`${deployFile} updated.`);
  return Promise.resolve();
}

function watchDeploy() {
  const watchers = [];
  for (const folder of schemaFolders) {
    const fullPath = path.join(__dirname, folder);
    if (fs.existsSync(fullPath)) {
      watchers.push(gulp.watch(`${folder}/**/*.sql`, { cwd: __dirname }, updateDeploy));
    }
  }
  if (watchers.length === 0) {
    console.log('No schema folders found to watch.');
  } else {
    console.log(`Watching ${schemaFolders.filter(f => fs.existsSync(path.join(__dirname, f))).join(', ')} for changes...`);
  }
  return Promise.resolve();
}

exports.default = updateDeploy;
exports['update-deploy'] = updateDeploy;
exports.watch = watchDeploy;
