CREATE TABLE IF NOT EXISTS public."ImageGeneration" (
    "Id" SERIAL PRIMARY KEY,
    "ModelKey" VARCHAR(100) NOT NULL DEFAULT '',
    "Name" VARCHAR(255) NOT NULL DEFAULT '',
    "Model" VARCHAR(255) NOT NULL DEFAULT '',
    "CPMITTokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "CPMIITokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "CPMOTokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "Type" INTEGER NOT NULL DEFAULT 0,
    "CP1K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP2K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP4K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP8K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "Active" BOOLEAN NOT NULL DEFAULT TRUE,
    "DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
