CREATE TABLE IF NOT EXISTS public."ImageGeneration" (
    "Id" SERIAL PRIMARY KEY,
    "ModelKey" VARCHAR(100) NOT NULL DEFAULT '',
    "Name" VARCHAR(255) NOT NULL DEFAULT '',
    "Model" VARCHAR(255) NOT NULL DEFAULT '',
    "CPMITTokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "CPMIITokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "CPMOTokens" DECIMAL(10,4) NOT NULL DEFAULT 0,
    "Type" INTEGER NOT NULL DEFAULT 0,
    "CP1K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP2K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP4K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "CP8K" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "WorkflowJson" TEXT NULL DEFAULT NULL,
    "PromptPath" TEXT NULL DEFAULT NULL,
    "DepthMapPath" TEXT NULL DEFAULT NULL,
    "InputImagesPath" TEXT NULL DEFAULT NULL,
    "SeedPath" TEXT NULL DEFAULT NULL,
    "Prompt" TEXT NULL DEFAULT NULL,
    "EndpointUrl" TEXT NULL DEFAULT NULL,
    "ParamMappings" TEXT NULL DEFAULT NULL,
    "PricingType" INTEGER NOT NULL DEFAULT 0,
    "Active" BOOLEAN NOT NULL DEFAULT TRUE,
    "DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Add columns if they don't exist (for existing databases)
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "WorkflowJson" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "PromptPath" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "DepthMapPath" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "InputImagesPath" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "SeedPath" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "Prompt" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "EndpointUrl" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "ParamMappings" TEXT NULL DEFAULT NULL;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "PricingType" INTEGER NOT NULL DEFAULT 0;
