CREATE TABLE IF NOT EXISTS public."LLM_Models" (
    "modelId" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL DEFAULT '',
    "model" VARCHAR(255) NOT NULL DEFAULT '',
    "endpoint" VARCHAR(500) NOT NULL DEFAULT '',
    "privateKey" VARCHAR(500) NOT NULL DEFAULT '',
    "type" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "preferred" BOOLEAN NOT NULL DEFAULT FALSE,
    "extraBody" TEXT NOT NULL DEFAULT '',
    "datecreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateupdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
