CREATE TABLE IF NOT EXISTS public."Products" (
    "Id" SERIAL PRIMARY KEY,
    "Title" VARCHAR(255) NOT NULL,
    "Price" INTEGER NOT NULL DEFAULT 0,
    "Tokens" INTEGER NOT NULL DEFAULT 0,
    "Archived" BOOLEAN NOT NULL DEFAULT FALSE,
    "DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
