<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <Target Name="KillRunningInstance" BeforeTargets="Build">
    <Exec Command="taskkill /F /IM TextureGen3D.Upscaler.exe 2>nul" IgnoreExitCode="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250506" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
  </ItemGroup>

</Project>
